language: python
services:
        - redis-server
before_script:
        - pip install pyflakes
        - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
script:
        - python -m unittest tests.testObjects
